# NLP
## Sentiment Analysis

Imports

In [1]:
import pandas as pd
import numpy as np 
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('../dataset/IMDB Dataset.csv')

df.sample(5)

                                                  review sentiment
13455  This thought long lost flick sometimes comes a...  negative
12356  Mindless dribble about the second coming of Ch...  negative
231    I think this is one hell of a movie..............  positive
42260  Hargh... this film is so bad it's almost good....  negative
25892  I give this marriage 3 years and thats stretch...  negative

In [ ]:
df.describe()

                                                   review sentiment
count                                               50000     50000
unique                                              49582         2
top     Loved today's show!!! It was a variety and not...  positive
freq                                                    5     25000

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   review     50000 non-null  object
 1   sentiment  50000 non-null  object
dtypes: object(2)
memory usage: 781.4+ KB